using Core.Entities.Concrete;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System.Collections.Generic;
using System.Linq;

namespace DataAccess.Concrete.Configurations
{
    public class GroupClaimEntityConfiguration : IEntityTypeConfiguration<GroupClaim>
    {
        public void Configure(EntityTypeBuilder<GroupClaim> builder)
        {
            builder.HasKey(x => new { x.GroupId, x.ClaimId });

            builder.HasData(

              new GroupClaim { GroupId = 1, ClaimId = 11 },
              new GroupClaim { GroupId = 1, ClaimId = 9 },
              new GroupClaim { GroupId = 1, ClaimId = 1 },
              new GroupClaim { GroupId = 4, ClaimId = 85 },
              new GroupClaim { GroupId = 4, ClaimId = 89 },
              new GroupClaim { GroupId = 4, ClaimId = 88 },
              new GroupClaim { GroupId = 4, ClaimId = 5 },
              new GroupClaim { GroupId = 4, ClaimId = 15 },
              new GroupClaim { GroupId = 4, ClaimId = 12 },
              new GroupClaim { GroupId = 3, ClaimId = 5 },
              new GroupClaim { GroupId = 3, ClaimId = 15 },
              new GroupClaim { GroupId = 3, ClaimId = 12 },


            new GroupClaim { GroupId = 2, ClaimId = 1 },
            new GroupClaim { GroupId = 2, ClaimId = 2 },
            new GroupClaim { GroupId = 2, ClaimId = 3 },
            new GroupClaim { GroupId = 2, ClaimId = 4 },
            new GroupClaim { GroupId = 2, ClaimId = 5 },
            new GroupClaim { GroupId = 2, ClaimId = 6 },
            new GroupClaim { GroupId = 2, ClaimId = 7 },
            new GroupClaim { GroupId = 2, ClaimId = 8 },
            new GroupClaim { GroupId = 2, ClaimId = 9 },
            new GroupClaim { GroupId = 2, ClaimId = 10 },
            new GroupClaim { GroupId = 2, ClaimId = 11 },
            new GroupClaim { GroupId = 2, ClaimId = 12 },
            new GroupClaim { GroupId = 2, ClaimId = 13 },
            new GroupClaim { GroupId = 2, ClaimId = 14 },
            new GroupClaim { GroupId = 2, ClaimId = 15 },
            new GroupClaim { GroupId = 2, ClaimId = 16 },
            new GroupClaim { GroupId = 2, ClaimId = 17 },
            new GroupClaim { GroupId = 2, ClaimId = 18 },
            new GroupClaim { GroupId = 2, ClaimId = 19 },
            new GroupClaim { GroupId = 2, ClaimId = 20 },
            new GroupClaim { GroupId = 2, ClaimId = 21 },
            new GroupClaim { GroupId = 2, ClaimId = 22 },
            new GroupClaim { GroupId = 2, ClaimId = 23 },
            new GroupClaim { GroupId = 2, ClaimId = 24 },
            new GroupClaim { GroupId = 2, ClaimId = 25 },
            new GroupClaim { GroupId = 2, ClaimId = 26 },
            new GroupClaim { GroupId = 2, ClaimId = 27 },
            new GroupClaim { GroupId = 2, ClaimId = 28 },
            new GroupClaim { GroupId = 2, ClaimId = 29 },
            new GroupClaim { GroupId = 2, ClaimId = 30 },
            new GroupClaim { GroupId = 2, ClaimId = 31 },
            new GroupClaim { GroupId = 2, ClaimId = 32 },
            new GroupClaim { GroupId = 2, ClaimId = 33 },
            new GroupClaim { GroupId = 2, ClaimId = 34 },
            new GroupClaim { GroupId = 2, ClaimId = 35 },
            new GroupClaim { GroupId = 2, ClaimId = 36 },
            new GroupClaim { GroupId = 2, ClaimId = 37 },
            new GroupClaim { GroupId = 2, ClaimId = 38 },
            new GroupClaim { GroupId = 2, ClaimId = 39 },
            new GroupClaim { GroupId = 2, ClaimId = 40 },
            new GroupClaim { GroupId = 2, ClaimId = 41 },
            new GroupClaim { GroupId = 2, ClaimId = 42 },
            new GroupClaim { GroupId = 2, ClaimId = 43 },
            new GroupClaim { GroupId = 2, ClaimId = 44 },
            new GroupClaim { GroupId = 2, ClaimId = 45 },
            new GroupClaim { GroupId = 2, ClaimId = 46 },
            new GroupClaim { GroupId = 2, ClaimId = 47 },
            new GroupClaim { GroupId = 2, ClaimId = 48 },
            new GroupClaim { GroupId = 2, ClaimId = 49 },
            new GroupClaim { GroupId = 2, ClaimId = 50 },
            new GroupClaim { GroupId = 2, ClaimId = 51 },
            new GroupClaim { GroupId = 2, ClaimId = 52 },
            new GroupClaim { GroupId = 2, ClaimId = 53 },
            new GroupClaim { GroupId = 2, ClaimId = 54 },
            new GroupClaim { GroupId = 2, ClaimId = 55 },
            new GroupClaim { GroupId = 2, ClaimId = 56 },
            new GroupClaim { GroupId = 2, ClaimId = 57 },
            new GroupClaim { GroupId = 2, ClaimId = 58 },
            new GroupClaim { GroupId = 2, ClaimId = 59 },
            new GroupClaim { GroupId = 2, ClaimId = 60 },
            new GroupClaim { GroupId = 2, ClaimId = 61 },
            new GroupClaim { GroupId = 2, ClaimId = 62 },
            new GroupClaim { GroupId = 2, ClaimId = 63 },
            new GroupClaim { GroupId = 2, ClaimId = 64 },
            new GroupClaim { GroupId = 2, ClaimId = 65 },
            new GroupClaim { GroupId = 2, ClaimId = 66 },
            new GroupClaim { GroupId = 2, ClaimId = 67 },
            new GroupClaim { GroupId = 2, ClaimId = 68 },
            new GroupClaim { GroupId = 2, ClaimId = 69 },
            new GroupClaim { GroupId = 2, ClaimId = 70 },
            new GroupClaim { GroupId = 2, ClaimId = 71 },
            new GroupClaim { GroupId = 2, ClaimId = 72 },
            new GroupClaim { GroupId = 2, ClaimId = 73 },
            new GroupClaim { GroupId = 2, ClaimId = 74 },
            new GroupClaim { GroupId = 2, ClaimId = 75 },
            new GroupClaim { GroupId = 2, ClaimId = 76 },
            new GroupClaim { GroupId = 2, ClaimId = 77 },
            new GroupClaim { GroupId = 2, ClaimId = 78 },
            new GroupClaim { GroupId = 2, ClaimId = 79 },
            new GroupClaim { GroupId = 2, ClaimId = 80 },
            new GroupClaim { GroupId = 2, ClaimId = 81 },
            new GroupClaim { GroupId = 2, ClaimId = 82 },
            new GroupClaim { GroupId = 2, ClaimId = 83 },
            new GroupClaim { GroupId = 2, ClaimId = 84 },
            new GroupClaim { GroupId = 2, ClaimId = 85 },
            new GroupClaim { GroupId = 2, ClaimId = 86 },
            new GroupClaim { GroupId = 2, ClaimId = 87 },
            new GroupClaim { GroupId = 2, ClaimId = 88 },
            new GroupClaim { GroupId = 2, ClaimId = 89 },
            new GroupClaim { GroupId = 2, ClaimId = 90 },
            new GroupClaim { GroupId = 2, ClaimId = 91 },
            new GroupClaim { GroupId = 2, ClaimId = 92 },
            new GroupClaim { GroupId = 2, ClaimId = 93 },
            new GroupClaim { GroupId = 2, ClaimId = 94 },
            new GroupClaim { GroupId = 2, ClaimId = 95 },
            new GroupClaim { GroupId = 2, ClaimId = 96 }

            );
        }
    }
}
